///////////////////////////////////////////////////////////
//  Inasistencia.cs
//  Implementation of the Class Inasistencia
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:50
//  Original author: orkus
///////////////////////////////////////////////////////////



using EDUAR_Entities.Shared;
using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class Inasistencia: DTBase
    {
        public int idInasistencia { get; set; }
        private DateTime _fecha;
        private MotivoAusencia _motivo;

        public Inasistencia()
        {

        }

        ~Inasistencia()
        {

        }

        public virtual void Dispose()
        {

        }

        public DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                _fecha = value;
            }
        }

        public MotivoAusencia motivo
        {
            get
            {
                return _motivo;
            }
            set
            {
                _motivo = value;
            }
        }

    }//end Inasistencia
}