///////////////////////////////////////////////////////////
//  TipoSancion.cs
//  Implementation of the Class TipoSancion
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:56
//  Original author: orkus
///////////////////////////////////////////////////////////


using System;
using EDUAR_Entities.Shared;
namespace EDUAR_Entities
{
    [Serializable]
    public class TipoSancion: DTBase
    {
        private int _idTipoSancion;

        public int idTipoSancion
        {
            get { return _idTipoSancion; }
            set { _idTipoSancion = value; }
        }

        private int _idTipoSancionTransaccional;

        public int idTipoSancionTransaccional
        {
            get { return _idTipoSancionTransaccional; }
            set { _idTipoSancionTransaccional = value; }
        }

        private string _descripcion;
        private string _nombre;

        public TipoSancion()
        {

        }

        ~TipoSancion()
        {

        }

        public virtual void Dispose()
        {

        }

        public string descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                _descripcion = value;
            }
        }

        public string nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                _nombre = value;
            }
        }

    }//end TipoSancion
}