///////////////////////////////////////////////////////////
//  FeriadosYFechasEspeciales.cs
//  Implementation of the Class FeriadosYFechasEspeciales
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:49
//  Original author: orkus
///////////////////////////////////////////////////////////

using System;
using EDUAR_Entities.Shared;
namespace EDUAR_Entities
{
    [Serializable]
    public class FeriadosYFechasEspeciales: DTBase
    {
        public int idFeriado { get; set; }
		public string descripcion { get; set; }
		public DateTime fecha { get; set; }

        public FeriadosYFechasEspeciales()
        {

        }

        ~FeriadosYFechasEspeciales()
        {

        }

        public virtual void Dispose()
        {

        }
    }//end FeriadosYFechasEspeciales
}