///////////////////////////////////////////////////////////
//  Asignatura.cs
//  Implementation of the Class Asignatura
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:44
//  Original author: orkus
///////////////////////////////////////////////////////////



namespace EDUAR_Entities
{
    public class Asignatura
    {

        private Contenido _contenidos;
        private Curso _curso;
        private DiasHorarios _diasHorarios;
        private Docente _docente;
        private string _nombre;
        private int _idAsignatura;

        public int idAsignatura
        {
            get { return _idAsignatura; }
            set { _idAsignatura = value; }
        }
        private int _idAsignaturaTransaccional;

        public int idAsignaturaTransaccional
        {
            get { return _idAsignaturaTransaccional; }
            set { _idAsignaturaTransaccional = value; }
        }

        public Asignatura()
        {

        }

        ~Asignatura()
        {

        }

        public virtual void Dispose()
        {

        }

        public Contenido contenidos
        {
            get
            {
                return _contenidos;
            }
            set
            {
                _contenidos = value;
            }
        }

        public Curso curso
        {
            get
            {
                return _curso;
            }
            set
            {
                _curso = value;
            }
        }

        public DiasHorarios diasHorarios
        {
            get
            {
                return _diasHorarios;
            }
            set
            {
                _diasHorarios = value;
            }
        }

        public Docente docente
        {
            get
            {
                return _docente;
            }
            set
            {
                _docente = value;
            }
        }

        public string nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                _nombre = value;
            }
        }

    }//end Asignatura
}