///////////////////////////////////////////////////////////
//  Calificacion.cs
//  Implementation of the Class Calificacion
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:45
//  Original author: orkus
///////////////////////////////////////////////////////////


using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class Calificacion
    {
        public string observacion { get; set; }
        public int idCalificacion { get; set; }
        public int idCalificacionTransaccional { get; set; }
        public Asignatura asignatura { get; set; }
        public ValoresEscalaCalificacion escala { get; set; }
        public DateTime fecha { get; set; }
        public Periodo periodo { get; set; }
        public Alumno alumno { get; set; }
        public InstanciaCalificacion instanciaCalificacion { get; set; }

        public Calificacion()
        {
            asignatura = new Asignatura();
            escala = new ValoresEscalaCalificacion();
            periodo = new Periodo();
            alumno = new Alumno();
            instanciaCalificacion = new InstanciaCalificacion();
        }

        ~Calificacion()
        {

        }

        public virtual void Dispose()
        {

        }
    }//end Calificacion
}