///////////////////////////////////////////////////////////
//  Periodo.cs
//  Implementation of the Class Periodo
//  Generated by Enterprise Architect
//  Created on:      23-jun-2011 19:30:00
//  Original author: Laura Pastorino
///////////////////////////////////////////////////////////


using System;
using EDUAR_Entities.Shared;

namespace EDUAR_Entities
{
    [Serializable]
    public class Periodo: DTBase
    {
        private int _idPeriodo;

        public int idPeriodo
        {
            get { return _idPeriodo; }
            set { _idPeriodo = value; }
        }
        private int _idPeriodoTransaccional;

        public int idPeriodoTransaccional
        {
            get { return _idPeriodoTransaccional; }
            set { _idPeriodoTransaccional = value; }
        }

        private CicloLectivo _cicloLectivo;

        public CicloLectivo cicloLectivo
        {
            get { return _cicloLectivo; }
            set { _cicloLectivo = value; }
        }
        private DateTime _fechaFin;

        public DateTime fechaFin
        {
            get { return _fechaFin; }
            set { _fechaFin = value; }
        }
        private DateTime _fechaInicio;

        public DateTime fechaInicio
        {
            get { return _fechaInicio; }
            set { _fechaInicio = value; }
        }
        private string _nombre;

        public string nombre
        {
            get { return _nombre; }
            set { _nombre = value; }
        }

        public Periodo()
        {

        }

        ~Periodo()
        {

        }

        public virtual void Dispose()
        {

        }
    }//end Periodo
}