///////////////////////////////////////////////////////////
//  TipoEventoInstitucional.cs
//  Implementation of the Class TipoEventoInstitucional
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:56
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////

using EDUAR_Entities.Shared;
using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class TipoEventoInstitucional:DTBase
    {

        public int idTipoEventoInstitucional { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }

        public TipoEventoInstitucional()
        {
            descripcion = string.Empty;
            activo = true;
        }

        ~TipoEventoInstitucional()
        {

        }

        public virtual void Dispose()
        {

        }

        }

}