///////////////////////////////////////////////////////////
//  PlanificacionAnualAsignatura.cs
//  Implementation of the Class PlanificacionAnualAsignatura
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:54
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////
using EDUAR_Entities.Shared;
using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class PlanificacionAnualAsignatura: DTBase
    {
        public int idPlanificacionAnualAsignatura { get; set; }
        public Asignatura _asignatura;
        private Docente _docente;

        public PlanificacionAnualAsignatura()
        {

        }

        ~PlanificacionAnualAsignatura()
        {

        }

        public virtual void Dispose()
        {

        }

        public Asignatura asignatura
        {
            get
            {
                return _asignatura;
            }
            set
            {
                _asignatura = value;
            }
        }

        public Docente docente
        {
            get
            {
                return _docente;
            }
            set
            {
                _docente = value;
            }
        }

    }//end PlanificacionAnualAsignatura
}