///////////////////////////////////////////////////////////
//  BibliografiaRecomendadaContenido.cs
//  Implementation of the Class BibliografiaRecomendadaContenido
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:45
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////



namespace EDUAR_Entities
{
    public class BibliografiaRecomendadaContenido
    {

        private string _clasificacion;
        private string _nombreLibro;

        public BibliografiaRecomendadaContenido()
        {

        }

        ~BibliografiaRecomendadaContenido()
        {

        }

        public virtual void Dispose()
        {

        }

        public string clasificacion
        {
            get
            {
                return _clasificacion;
            }
            set
            {
                _clasificacion = value;
            }
        }

        public string nombreLibro
        {
            get
            {
                return _nombreLibro;
            }
            set
            {
                _nombreLibro = value;
            }
        }

    }//end BibliografiaRecomendadaContenido
}