///////////////////////////////////////////////////////////
//  DiasHorarios.cs
//  Implementation of the Class DiasHorarios
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:47
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////



using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class DiasHorarios
    {

        private string _dia;
        /// <summary>
        /// Hace referencia a si es la primer hora, la segunda, terera, etc.
        /// </summary>
        private int _hora;
        private double _horasCatedra;

        public DiasHorarios()
        {

        }

        ~DiasHorarios()
        {

        }

        public virtual void Dispose()
        {

        }

        public string dia
        {
            get
            {
                return _dia;
            }
            set
            {
                _dia = value;
            }
        }

        /// <summary>
        /// Hace referencia a si es la primer hora, la segunda, terera, etc.
        /// </summary>
        public int hora
        {
            get
            {
                return _hora;
            }
            set
            {
                _hora = value;
            }
        }

        public double horasCatedra
        {
            get
            {
                return _horasCatedra;
            }
            set
            {
                _horasCatedra = value;
            }
        }

    }//end DiasHorarios
}