///////////////////////////////////////////////////////////
//  TemaContenido.cs
//  Implementation of the Class TemaContenido
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:56
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////


namespace EDUAR_Entities
{

    public class TemaContenido
    {

        private string _tema;

        public TemaContenido()
        {

        }

        ~TemaContenido()
        {

        }

        public virtual void Dispose()
        {

        }

        public string tema
        {
            get
            {
                return _tema;
            }
            set
            {
                _tema = value;
            }
        }

    }//end TemaContenido
}