///////////////////////////////////////////////////////////
//  Tutor.cs
//  Implementation of the Class Tutor
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:57
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace EDUAR_Entities
{
    [Serializable]
    public class Tutor : Persona
    {
        public int idTutor { get; set; }
        public int idTutorTransaccional { get; set; }
        public string TelefonoFijoTrabajo { get; set; }
        public TipoTutor tipoTutor { get; set; }

        public Tutor()
        {

        }

        ~Tutor()
        {

        }
    }//end Tutor
}