using System;
using EDUAR_Entities.Shared;
///////////////////////////////////////////////////////////
//  Citacion.cs
//  Implementation of the Class Citacion
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:45
//  Original author: orkus
///////////////////////////////////////////////////////////


namespace EDUAR_Entities
{
    [Serializable]
    public class Citacion:DTBase
    {
        private int _idCitacion;
        private string _detalles;
        private DateTime _fecha;
        private Usuario _gestorEvento;
        private DateTime _horario;
        private MotivoCitacion _motivoCitacion;
        private Tutor _tutor;

        public Citacion()
        {

        }

        ~Citacion()
        {

        }

        public virtual void Dispose()
        {

        }

        public int idCitacion
        {
            get { return _idCitacion; }
            set { _idCitacion = value; }
        }

        public string detalles
        {
            get
            {
                return _detalles;
            }
            set
            {
                _detalles = value;
            }
        }

        public DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                _fecha = value;
            }
        }

        public Usuario gestorEvento
        {
            get
            {
                return _gestorEvento;
            }
            set
            {
                _gestorEvento = value;
            }
        }

        public DateTime horario
        {
            get
            {
                return _horario;
            }
            set
            {
                _horario = value;
            }
        }

        public MotivoCitacion motivoCitacion
        {
            get
            {
                return _motivoCitacion;
            }
            set
            {
                _motivoCitacion = value;
            }
        }

        public Tutor tutor
        {
            get
            {
                return _tutor;
            }
            set
            {
                _tutor = value;
            }
        }

    }//end Citacion
}