///////////////////////////////////////////////////////////
//  EventoInstitucional.cs
//  Implementation of the Class EventoInstitucional
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:49
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////


using System;
namespace EDUAR_Entities
{

    public class EventoInstitucional
    {
        private DateTime _fecha;
        private string _motivo;
        private string _nombre;
        private Usuario _organizador;
        private TipoEventoInstitucional _tipoEventoInstitucional;

        public EventoInstitucional()
        {

        }

        ~EventoInstitucional()
        {

        }

        public virtual void Dispose()
        {

        }

        public DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                _fecha = value;
            }
        }

        public string motivo
        {
            get
            {
                return _motivo;
            }
            set
            {
                _motivo = value;
            }
        }

        public string nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                _nombre = value;
            }
        }

        public Usuario organizador
        {
            get
            {
                return _organizador;
            }
            set
            {
                _organizador = value;
            }
        }

        public TipoEventoInstitucional tipoEventoInstitucional
        {
            get
            {
                return _tipoEventoInstitucional;
            }
            set
            {
                _tipoEventoInstitucional = value;
            }
        }

    }//end EventoInstitucional
}