///////////////////////////////////////////////////////////
//  TipoEventoInstitucional.cs
//  Implementation of the Class TipoEventoInstitucional
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:56
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////


namespace EDUAR_Entities
{

    public class TipoEventoInstitucional
    {

        private string _descripcion;

        public TipoEventoInstitucional()
        {

        }

        ~TipoEventoInstitucional()
        {

        }

        public virtual void Dispose()
        {

        }

        public string descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                _descripcion = value;
            }
        }

    }//end TipoEventoInstitucional
}