USE [master]
GO

/****** Object:  Database [EDUAR]    Script Date: 09/10/2013 19:51:43 ******/
CREATE DATABASE [EDUAR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EDUAR', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\EDUAR.mdf' , SIZE = 11328KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EDUAR_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\EDUAR_DEV_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EDUAR] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EDUAR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EDUAR] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EDUAR] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EDUAR] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EDUAR] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EDUAR] SET ARITHABORT OFF 
GO

ALTER DATABASE [EDUAR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EDUAR] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [EDUAR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EDUAR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EDUAR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EDUAR] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EDUAR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EDUAR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EDUAR] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EDUAR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EDUAR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EDUAR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EDUAR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EDUAR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EDUAR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EDUAR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EDUAR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EDUAR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EDUAR] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EDUAR] SET  MULTI_USER 
GO

ALTER DATABASE [EDUAR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EDUAR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EDUAR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EDUAR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EDUAR] SET  READ_WRITE 
GO