///////////////////////////////////////////////////////////
//  Escala.cs
//  Implementation of the Class Escala
//  Generated by Enterprise Architect
//  Created on:      18-mar-2013 16:21:48
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////

using EDUAR_Entities.Shared;
using System;

namespace EDUAR_Entities
{
    [Serializable]
    public class ValorEscalaMedicion : DTBase
    {
        public int idValorEscala { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int idEscalaMedicion { get; set; }

        public ValorEscalaMedicion()
        {
        }

        ~ValorEscalaMedicion()
        {
        }

        public virtual void Dispose()
        {
        }

    }//end Escala
}