///////////////////////////////////////////////////////////
//  Permiso.cs
//  Implementation of the Class Permiso
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:52
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////



using EDUAR_Entities.Shared;
using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class Permiso:DTBase
    {
        public int idPermiso { get; set; }
        public Object elemento { get; set; }
        public string nombre { get; set; }
        public string privilegio { get; set; }

        public Permiso()
        {

        }

        ~Permiso()
        {

        }

        public virtual void Dispose()
        {

        }

    }//end Permiso
}