///////////////////////////////////////////////////////////
//  Mensaje.cs
//  Implementation of the Class Mensaje
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:50
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using EDUAR_Entities.Shared;
using EDUAR_Entities.Security;
namespace EDUAR_Entities
{
    [Serializable]
    public class Mensaje : DTBase
    {
        public int idMensaje { get; set; }
		public int idMensajeDestinatario { get; set; }
        public List<Persona> ListaDestinatarios { get; set; }
        public DateTime fechaEnvio { get; set; }
        public DateTime horaEnvio { get; set; }
        public Persona remitente { get; set; }
		public string listaIDMensaje { get; set; }
		public CursoCicloLectivo cursoCicloLectivo { get; set; }

		/// <summary>
		/// Este atributo SOLO SE UTILIZA PARA RECUPERAR LOS MENSAJES EN LOS QUE UN USUARIO APARECE COMO DESTINATARIO!!!
		/// </summary>
		/// <value>
		/// The destinatario.
		/// </value>
		public Persona destinatario { get; set; }
        public string asuntoMensaje { get; set; }
		public string textoMensaje { get; set; }
		public bool activo { get; set; }

		/// <summary>
		/// Se utiliza para recuperar la lista de mensajes de un usuario e indicar si ha sido leido o no.
		/// Gets or sets a value indicating whether this <see cref="Mensaje"/> is leido.
		/// </summary>
		/// <value>
		///   <c>true</c> if leido; otherwise, <c>false</c>.
		/// </value>
		public bool leido { get; set; }

        public Mensaje()
        {
            ListaDestinatarios = new List<Persona>();
			remitente = new Persona();
			destinatario = new Persona();
			activo = true;
			cursoCicloLectivo = new CursoCicloLectivo();
        }

        ~Mensaje()
        {

        }

        public virtual void Dispose()
        {

        }
    }//end Mensaje
}