///////////////////////////////////////////////////////////
//  Mensaje.cs
//  Implementation of the Class Mensaje
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:50
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using EDUAR_Entities.Shared;
using EDUAR_Entities.Security;
namespace EDUAR_Entities
{
    [Serializable]
    public class Mensaje : DTBase
    {
        public int idMensaje { get; set; }
        public List<Persona> ListaDestinatarios { get; set; }
        public DateTime fechaEnvio { get; set; }
        public DateTime horaEnvio { get; set; }
        public DTUsuario remitente { get; set; }
        public string textoMensaje { get; set; }
		public bool activo { get; set; }

        public Mensaje()
        {
            ListaDestinatarios = new List<Persona>();
            remitente = new DTUsuario();
			activo = true;
        }

        ~Mensaje()
        {

        }

        public virtual void Dispose()
        {

        }
    }//end Mensaje
}