///////////////////////////////////////////////////////////
//  Contenido.cs
//  Implementation of the Class Contenido
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:46
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using EDUAR_Entities.Shared;
namespace EDUAR_Entities
{
	[Serializable]
	public class Contenido : DTBase
	{
		public int idContenido { get; set; }
        public int idCurricula { get; set; }
		public string descripcion { get; set; }
        public bool activo { get; set; }
        public DateTime fechaBaja { get; set; }
        public Persona usuarioBaja { get; set; }
		public List<TemaContenido> listaContenidos { get; set; }

		public Contenido(int unIdCurricula)
		{
            idCurricula = unIdCurricula;
            listaContenidos = new List<TemaContenido>();
            usuarioBaja = new Persona();
		}

        public Contenido()
        {
            listaContenidos = new List<TemaContenido>();
            usuarioBaja = new Persona();
        }

		~Contenido()
		{

		}

		public virtual void Dispose()
		{

		}
	}//end Contenido
}