using System;
using System.Collections.Generic;
///////////////////////////////////////////////////////////
//  DiaHorario.cs
//  Implementation of the Class DiaHorario
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:47
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////
using EDUAR_Entities.Shared;
using EDUAR_Utility.Enumeraciones;


namespace EDUAR_Entities
{
	[Serializable]
	public class DiasHorarios : DTBase
	{
		public int idDiaHorario { get; set; }
		public int idAsignaturaCurso { get; set; }
		public int idDiaHorarioTransaccional { get; set; }
		public enumDiasSemana unDia { get; set; }
		public List<Modulo> modulos { get; set; }
		public int idCursoTransaccional { get; set; }
		public int idAsignaturaTransaccional { get; set; }
        public int idNivelTransaccional { get; set; }

		/// <summary>
		/// Initializes a new instance of the <see cref="DiasHorarios"/> class.
		/// </summary>
		public DiasHorarios()
		{
			modulos = new List<Modulo>();
		}

		/// <summary>
		/// Releases unmanaged resources and performs other cleanup operations before the
		/// <see cref="DiasHorarios"/> is reclaimed by garbage collection.
		/// </summary>
		~DiasHorarios()
		{

		}

		/// <summary>
		/// Releases unmanaged and - optionally - managed resources
		/// </summary>
		public virtual void Dispose()
		{

		}
	}//end DiaHorario
}