///////////////////////////////////////////////////////////
//  TemasPlanificadosAsignatura.cs
//  Implementation of the Class TemasPlanificadosAsignatura
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:56
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////
using System;
using EDUAR_Entities.Shared;
namespace EDUAR_Entities
{
	[Serializable]
	public class TemaPlanificacionAnual : DTBase
	{
		public int idTemaPlanificacion { get; set; }
		public int idPlanificacionAnual { get; set; }
		public string contenidosConceptuales { get; set; }
		public string contenidosProcedimentales { get; set; }
		public string contenidosActitudinales { get; set; }
		public string estrategiasAprendizaje { get; set; }
		public string criteriosEvaluacion { get; set; }
		public string instrumentosEvaluacion { get; set; }
		public DateTime? fechaInicioEstimada { get; set; }
		public DateTime? fechaFinEstimada { get; set; }
		public string observaciones { get; set; }
		public Asignatura asignatura { get; set; }

		public TemaPlanificacionAnual()
		{
			asignatura = new Asignatura();
		}

		~TemaPlanificacionAnual()
		{

		}

		public virtual void Dispose()
		{

		}
	}//end TemasPlanificadosAsignatura
}