///////////////////////////////////////////////////////////
//  Novedad.cs
//  Implementation of the Class Novedad
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:51
//  Original author: orkus
///////////////////////////////////////////////////////////
using EDUAR_Entities.Shared;

using System.Collections.Generic;
using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class Novedad:DTBase
    {
        public int idNovedad { get; set; }
        public Curso curso { get; set; }
        public DateTime fecha { get; set; }
        public Usuario informante { get; set; }
        public List<Usuario> involucrados { get; set; }
        public Usuario usuario { get; set; }
        public string novedad { get; set; }
        public TipoNovedad tipoNovedad { get; set; }

        public Novedad()
        {

        }

        ~Novedad()
        {

        }

        public virtual void Dispose()
        {

        }

    }//end Novedad
}