using System;
///////////////////////////////////////////////////////////
//  Novedad.cs
//  Implementation of the Class Novedad
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:51
//  Original author: orkus
///////////////////////////////////////////////////////////
using EDUAR_Entities.Shared;
namespace EDUAR_Entities
{
	[Serializable]
	public class Novedad : DTBase
	{
		public int idNovedad { get; set; }
		public Curso curso { get; set; }
		public DateTime fecha { get; set; }
		public Persona usuario { get; set; }
		public string observaciones { get; set; }
		public TipoNovedad tipo { get; set; }
		public EstadoNovedad estado { get; set; }
		public Novedad novedadPadre { get; set; }

		public Novedad()
		{
			tipo = new TipoNovedad();
			estado = new EstadoNovedad();
			usuario = new Persona();
			curso = new Curso();
		}

		~Novedad()
		{

		}

		public virtual void Dispose()
		{

		}

	}//end Novedad
}