///////////////////////////////////////////////////////////
//  TipoNovedad.cs
//  Implementation of the Class TipoNovedad
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:56
//  Original author: orkus
///////////////////////////////////////////////////////////

using EDUAR_Entities.Shared;
using System;
namespace EDUAR_Entities
{
	[Serializable]
	public class TipoNovedad : DTBase
	{
		public int idTipoNovedad { get; set; }
		public string nombre { get; set; }

		public TipoNovedad()
		{

		}

		~TipoNovedad()
		{

		}

		public virtual void Dispose()
		{

		}

	}//end TipoNovedad
}