///////////////////////////////////////////////////////////
//  Evaluacion.cs
//  Implementation of the Class Evaluacion
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:49
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////

using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class Evaluacion
    {
        private Asignatura _asignatura;
        private DateTime _fecha;

        public Evaluacion()
        {

        }

        ~Evaluacion()
        {

        }

        public virtual void Dispose()
        {

        }

        public Asignatura asignatura
        {
            get
            {
                return _asignatura;
            }
            set
            {
                _asignatura = value;
            }
        }

        public DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                _fecha = value;
            }
        }

    }//end Evaluacion
}