///////////////////////////////////////////////////////////
//  EventoInstitucional.cs
//  Implementation of the Class EventoInstitucional
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:49
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////


using System;
using EDUAR_Entities.Shared;
namespace EDUAR_Entities
{
    [Serializable]
    public class EventoInstitucional: DTBase
    {
        public int idEventoInstitucional { get; set; }
        public DateTime fecha { get; set; }
        public DateTime? hora { get; set; }
        public string detalle { get; set; }
        public string lugar { get; set; }
        public string titulo { get; set; }
        public Persona organizador { get; set; }
        public TipoEventoInstitucional tipoEventoInstitucional { get; set; }
        public bool activo { get; set; }
        public DateTime fechaDesde { get; set; }
        public DateTime fechaHasta { get; set; }

        public EventoInstitucional()
        {
            organizador = new Persona();
            tipoEventoInstitucional = new TipoEventoInstitucional();
        }

        ~EventoInstitucional()
        {

        }

        public virtual void Dispose()
        {

        }

    }//end EventoInstitucional
}
