///////////////////////////////////////////////////////////
//  MotivoCitacion.cs
//  Implementation of the Class MotivoCitacion
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:51
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////

using EDUAR_Entities.Shared;
using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class MotivoCitacion:DTBase
    {
        private int _idMotivoCitacion;

       
        private string _descripcion;
        private string _nombre;

        public MotivoCitacion()
        {

        }

        ~MotivoCitacion()
        {

        }

        public virtual void Dispose()
        {

        }

        public int idMotivoCitacion
        {
            get { return _idMotivoCitacion; }
            set { _idMotivoCitacion = value; }
        }

        public string descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                _descripcion = value;
            }
        }

        public string nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                _nombre = value;
            }
        }

    }//end MotivoCitacion
}