///////////////////////////////////////////////////////////
//  Reunion.cs
//  Implementation of the Class Reunion
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:55
//  Original author: Belén
///////////////////////////////////////////////////////////

using EDUAR_Entities.Shared;
using System;

namespace EDUAR_Entities
{
    [Serializable]
    public class Reunion : DTBase
    {
        public int idReunion { get; set; }
        public DateTime horario { get; set; }
        public EventoAgenda evento { get; set; }

        public Reunion()
        {
            evento = new EventoAgenda();
        }

        ~Reunion()
        {

        }

        public virtual void Dispose()
        {

        }
                
    }//end Reunion
}