///////////////////////////////////////////////////////////
//  Reunion.cs
//  Implementation of the Class Reunion
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:55
//  Original author: Belén
///////////////////////////////////////////////////////////

using EDUAR_Entities.Shared;
using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class Reunion:DTBase
    {
        private int _idReunion;
        private Curso _curso;
        private DateTime _fecha;
        private Usuario _gestorReunion;
        private DateTime _horario;
        private string _motivo;

        public Reunion()
        {

        }

        ~Reunion()
        {

        }

        public virtual void Dispose()
        {

        }

        public int idReunion
        {
            get { return _idReunion; }
            set { _idReunion = value; }
        }

        public Curso curso
        {
            get
            {
                return _curso;
            }
            set
            {
                _curso = value;
            }
        }

        public DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                _fecha = value;
            }
        }

        public Usuario gestorReunion
        {
            get
            {
                return _gestorReunion;
            }
            set
            {
                _gestorReunion = value;
            }
        }

        public DateTime horario
        {
            get
            {
                return _horario;
            }
            set
            {
                _horario = value;
            }
        }

        public string motivo
        {
            get
            {
                return _motivo;
            }
            set
            {
                _motivo = value;
            }
        }

    }//end Reunion
}