///////////////////////////////////////////////////////////
//  Cargo.cs
//  Implementation of the Class Cargo
//  Generated by Enterprise Architect
//  Created on:      14-jun-2011 20:12:10
//  Original author: Laura Pastorino
///////////////////////////////////////////////////////////

namespace EDUAR_Entities
{
    public class CargoPersonal
    {
        private string _descripcion;
        private string _nombre;
        private int _idCargo;
        private int _idCargoTransaccional;
        private bool _activo;

        public bool activo
        {
            get { return _activo; }
            set { _activo = value; }
        }

        public int idCargo
        {
            get { return _idCargo; }
            set { _idCargo = value; }
        }
       

        public int idCargoTransaccional
        {
            get { return _idCargoTransaccional; }
            set { _idCargoTransaccional = value; }
        }

        public CargoPersonal()
        {

        }

        ~CargoPersonal()
        {

        }

        public virtual void Dispose()
        {

        }

        public string descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                _descripcion = value;
            }
        }

        public string nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                _nombre = value;
            }
        }

    }//end Cargo
}