///////////////////////////////////////////////////////////
//  Director.cs
//  Implementation of the Class Director
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:47
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////


using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class Director : Personal
    {

        public Director()
        {

        }

        ~Director()
        {

        }

        //public override void Dispose()
        //{

        //}

    }//end Director
}