///////////////////////////////////////////////////////////
//  Preceptor.cs
//  Implementation of the Class Preceptor
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:54
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////


using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class Preceptor : Personal
    {

        private Curso _cursos;

        public Preceptor()
        {

        }

        ~Preceptor()
        {

        }

        //public override void Dispose()
        //{

        //}

        public Curso cursos
        {
            get
            {
                return _cursos;
            }
            set
            {
                _cursos = value;
            }
        }

    }//end Preceptor
}