///////////////////////////////////////////////////////////
//  Psicopedagogo.cs
//  Implementation of the Class Psicopedagogo
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:55
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////


namespace EDUAR_Entities
{

    public class Psicopedagogo : Personal
    {

        public Psicopedagogo()
        {

        }

        ~Psicopedagogo()
        {

        }

        //public override void Dispose()
        //{

        //}

    }//end Psicopedagogo
}