///////////////////////////////////////////////////////////
//  Topico.cs
//  Implementation of the Class Topico
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:56
//  Original author: Pablo Nicoliello
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class Topico
    {

        private string _descripcionTopico;
        private string _nombreTopico;
        private List<Post> _posts;

        public Topico()
        {

        }

        ~Topico()
        {

        }

        public virtual void Dispose()
        {

        }

        public string descripcionTopico
        {
            get
            {
                return _descripcionTopico;
            }
            set
            {
                _descripcionTopico = value;
            }
        }

        public string nombreTopico
        {
            get
            {
                return _nombreTopico;
            }
            set
            {
                _nombreTopico = value;
            }
        }

        public List<Post> posts
        {
            get
            {
                return _posts;
            }
            set
            {
                _posts = value;
            }
        }

    }//end Topico
}