/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Objetos.Euler;
import Estructura.modeloTablaEuler;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sun.io.Converters;
import sun.org.mozilla.javascript.internal.ast.TryStatement;

/**
 *
 * @author Belén
 */
public class MetodoEuler extends javax.swing.JFrame {

    /**
     * Creates new form MetodoEuler
     */
    
    public static double x0;
    public static double Y0;
    public static double h;
    private static Euler aux[] = new Euler[2];
    public static double xfinal;
//public Principal principal=new Principal();

    public MetodoEuler() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static void setX0(double x0) {
        MetodoEuler.x0 = x0;
    }

    public static void setY0(double Y0) {
        MetodoEuler.Y0 = Y0;
    }

    public static void setH(double h) {
        MetodoEuler.h = h;
    }

//    public static double getX0() {
//        return x0;
//    }
//
//    public static double getY0() {
//        return Y0;
//    }
//
//    public static double getH() {
//        return h;
//    }

    public static double getXfinal() {
        return xfinal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Método Euler");
        setResizable(false);

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));

        jTable2.setModel(new Estructura.modeloTablaEuler());
        jScrollPane1.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Velocidad de Lanzamiento dy/dx = 0,6y^2 - 0,15 y + 8");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setName("lblResultado"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
        );

        jLabel3.getAccessibleContext().setAccessibleParent(this);

        jButton2.setText("Siguiente");
        jButton2.setActionCommand("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Cálculo del Tiempo de Lanzamiento");
        jLabel2.setToolTipText("");
        jLabel2.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
        //           principal= null;
//           principal = new Principal();
//           principal.setTiempoTardaLanzamiento(xfinal);
//           principal.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
////    private boolean tomarValoresIngresadosEuler() {
//        if (!textField1.getText().trim().equals("") && Double.parseDouble(textField1.getText()) != -1) {
//        x0 = Double.parseDouble(textField1.getText());
//        } else {
//            JOptionPane.showMessageDialog(this, "Debe ingresar un valor inicial de Xo.", "Faltan datos", JOptionPane.ERROR_MESSAGE);
//            textField1.requestFocus();
//            return false;
//        }
//        if (!textField2.getText().trim().equals("") && Double.parseDouble(textField2.getText()) != 0) {
//            Y0 = Double.parseDouble(textField2.getText());
//        } else {
//            JOptionPane.showMessageDialog(this, "Debe ingresar un valor inicial de Yo.", "Faltan datos", JOptionPane.ERROR_MESSAGE);
//            textField2.requestFocus();
//            return false;
//        }
//        if (!textField3.getText().trim().equals("") && Double.parseDouble(textField3.getText()) != 0) {
//            h = Double.parseDouble(textField3.getText());
//        } else {
//            JOptionPane.showMessageDialog(this, "Debe ingresar un valor inicial de h.", "Faltan datos", JOptionPane.ERROR_MESSAGE);
//            textField3.requestFocus();
//            return false;
//        }
//        return true;
//    }

   public double inicializarEuler( ) {

        for (int k = 0; k < 2; k++) {
            aux[k] = new Euler();
        }
        aux[1].setI(0);
        aux[1].setXi(x0);
        aux[1].setH(h);
        aux[1].setYi(Y0);
        aux[1].setDY(Y0);
        aux[1].setYprox();
        
        try {
            ((modeloTablaEuler) this.jTable2.getModel()).anhadeFila(aux[1]);
        } catch (Exception e) {
            System.out.println("ERROR!!!" + e.getMessage());
        }

//        System.out.println(aux[1].toString());
        try {
            while (aux[1].getYprox() > 0) {
                aux[0].copiaObj(aux[1]);
                aux[1] = new Euler();
                aux[1].recalculoEuler(aux[0]);
                try {
                    ((modeloTablaEuler) this.jTable2.getModel()).anhadeFila(aux[1]);
                } catch (Exception e) {
                    System.out.println("ERROR!!!" + e.getMessage());
                }
            }
        } catch (Exception e) {
            System.out.println("ERROR!!!" + e.getMessage());
        }
        xfinal  = aux[1].getXi();
        jLabel3.setText("Tiempo que tarda un deslizamiento: "+String.valueOf(xfinal)+" Segundos.");
        return aux[1].getXi();
    }

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MetodoEuler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MetodoEuler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MetodoEuler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MetodoEuler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MetodoEuler().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    public void limpiarValoresPreviosEuler() {
     Y0 = 0;
     x0 = 0;
     xfinal = 0;
     h = 0;
     //((modeloTablaEuler) this.jTable2.getModel()).anhadeFila(aux[1]);
     this.jTable2.removeAll();
     this.jTable2.removeEditor();
     jTable2.setModel(new Estructura.modeloTablaEuler());
             }
}
