///////////////////////////////////////////////////////////
//  MotivoSancion.cs
//  Implementation of the Class MotivoSancion
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:51
//  Original author: orkus
///////////////////////////////////////////////////////////
using EDUAR_Entities.Shared;
using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class MotivoSancion: DTBase
    {

        public string descripcion { get; set; }
        public int idMotivoSancion { get; set; }
        public int idMotivoSancionTransaccional { get; set; }

        public MotivoSancion()
        {

        }

        ~MotivoSancion()
        {

        }

        public virtual void Dispose()
        {

        }

    }//end MotivoSancion
}