///////////////////////////////////////////////////////////
//  Periodo.cs
//  Implementation of the Class Periodo
//  Generated by Enterprise Architect
//  Created on:      23-jun-2011 19:30:00
//  Original author: Laura Pastorino
///////////////////////////////////////////////////////////


using System;
using EDUAR_Entities.Shared;

namespace EDUAR_Entities
{
    [Serializable]
    public class Periodo: DTBase
    {
        public int idPeriodo { get; set; }
        public int idPeriodoTransaccional { get; set; }
        public CicloLectivo cicloLectivo { get; set; }
        public DateTime fechaFin { get; set; }
        public DateTime fechaInicio { get; set; }
        public string nombre { get; set; }

        public Periodo()
        {

        }

        ~Periodo()
        {

        }

        public virtual void Dispose()
        {

        }
    }//end Periodo
}