///////////////////////////////////////////////////////////
//  Asignatura.cs
//  Implementation of the Class Asignatura
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:44
//  Original author: orkus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using EDUAR_Entities.Shared;
namespace EDUAR_Entities
{
    [Serializable]
    public class Asignatura : DTBase
    {
        public List<Contenido> listaContenidos { get; set; }
        public Curso curso { get; set; }
        public DiasHorarios diasHorarios { get; set; }
        public Docente docente { get; set; }
        public string nombre { get; set; }
        public int idAsignatura { get; set; }
        public int idAsignaturaTransaccional { get; set; }

        public Asignatura()
        {
            listaContenidos = new List<Contenido>();
            curso = new Curso();
            diasHorarios = new DiasHorarios();
            docente = new Docente();
        }

        ~Asignatura()
        {

        }

        public virtual void Dispose()
        {

        }

    }//end Asignatura
}