///////////////////////////////////////////////////////////
//  Calificacion.cs
//  Implementation of the Class Calificacion
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:45
//  Original author: orkus
///////////////////////////////////////////////////////////


using System;
namespace EDUAR_Entities
{
    [Serializable]
    public class Calificacion
    {

        private Asignatura _asignatura;
        private ValoresEscalaCalificacion _escala;
        private DateTime _fecha;
        /// <summary>
        /// Por ahora es string, pero dependería de la escala a ser utilizada y luego ser
        /// parseada
        /// </summary>
        private string _observacion;
        private int _idCalificacion;
        private int _idCalificacionTransaccional;
        private Periodo _periodo;
        private Alumno _alumno;


        

        public Calificacion()
        {

        }

        ~Calificacion()
        {

        }

        public virtual void Dispose()
        {

        }

        public Asignatura asignatura
        {
            get
            {
                return _asignatura;
            }
            set
            {
                _asignatura = value;
            }
        }

        public ValoresEscalaCalificacion escala
        {
            get
            {
                return _escala;
            }
            set
            {
                _escala = value;
            }
        }

        public DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                _fecha = value;
            }
        }
        public int idCalificacion
        {
            get { 
                return _idCalificacion;
            }
            set {
                _idCalificacion = value;
            }
        }
        public int idCalificacionTransaccional
        {
            get
            {
                return _idCalificacionTransaccional;
            }
            set
            {
                _idCalificacionTransaccional = value;
            }
        }
        public Periodo periodo
        {
            get {
                return _periodo;
            }
            set {
                _periodo = value; 
            }
        }
        public Alumno alumno
        {
            get
            {
                if (_alumno == null)
                    _alumno = new Alumno();
                return _alumno;
            }
            set {
                _alumno = alumno;
            }
        }
        /// <summary>
        /// Por ahora es decimal, pero dependería de la escala a ser utilizada
        /// </summary>
        public string observacion
        {
            get
            {
                return _observacion;
            }
            set
            {
                _observacion = value;
            }
        }

    }//end Calificacion
}