///////////////////////////////////////////////////////////
//  MotivoAusencia.cs
//  Implementation of the Class MotivoAusencia
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:51
//  Original author: orkus
///////////////////////////////////////////////////////////


namespace EDUAR_Entities
{

    public class MotivoAusencia
    {

        private string _descripcion;
        private int _idMotivo;

        public MotivoAusencia()
        {

        }

        ~MotivoAusencia()
        {

        }

        public virtual void Dispose()
        {

        }

        public string descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                _descripcion = value;
            }
        }

        public int idMotivo
        {
            get
            {
                return _idMotivo;
            }
            set
            {
                _idMotivo = value;
            }
        }

    }//end MotivoAusencia
}