///////////////////////////////////////////////////////////
//  Nivel.cs
//  Implementation of the Class Nivel
//  Generated by Enterprise Architect
//  Created on:      20-jun-2011 16:21:51
//  Original author: orkus
///////////////////////////////////////////////////////////



namespace EDUAR_Entities
{
    public class Nivel
    {
        private int _idNivel;

        public int idNivel
        {
            get { return _idNivel; }
            set { _idNivel = value; }
        }
        private int _idNivelTransaccional;

        public int idNivelTransaccional
        {
            get { return _idNivelTransaccional; }
            set { _idNivelTransaccional = value; }
        }
        private string _nombre;

        public Nivel()
        {

        }

        ~Nivel()
        {

        }

        public virtual void Dispose()
        {

        }

        public string nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                _nombre = value;
            }
        }

    }//end Nivel
}